import { Category, PlanSection } from "../types";

export const categories: Category[] = [
  {
    key: "4g",
    label: "4G Internet",
    icon: "wifi",
    subs: [
      { key: "volume", label: "Volume Based" },
      { key: "special", label: "Special Offers" },
      { key: "home", label: "Home Broadband" },
      { key: "gahebuzo", label: "Gahebuzo Packs" },
      { key: "fixed", label: "Fixed LTE SMEs" },
      { key: "office", label: "Office Broadband" },
      { key: "network", label: "One Network" },
      { key: "education", label: "Education Products" },
      { key: "time", label: "Time-Base(MUP)" },
    ],
  },
  {
    key: "volte",
    label: "VoLTE",
    icon: "router",
    subs: [{ key: "packages", label: "Solektra Packages" }],
  },
  {
    key: "devices",
    label: "Devices",
    icon: "device-mobile",
    subs: [
      { key: "home", label: "4G routers" },
      { key: "smartphones", label: "Smartphones" },
    ],
  },
];

export const plansData: Record<string, PlanSection> = {
  "4g-volume": {
    title: "4G Internet — volume based",
    desc: "Daily , weekly and monthly data bundles. Buy once and use until it expires.",
    daily: [
      {
        id: "4gv-d1",
        vol: "60 MB",
        price: "100 RWF",
        priceRaw: 100,
        validity: "1 day",
        speed: "Up to 10 Mbps",
      },
      {
        id: "4gv-d2",
        vol: "150 MB",
        price: "200 RWF",
        priceRaw: 200,
        validity: "1 day",
        speed: "Up to 10 Mbps",
        popular: true,
      },
      {
        id: "4gv-d3",
        vol: "300 MB",
        price: "300 RWF",
        priceRaw: 300,
        validity: "1 day",
        speed: "Up to 20 Mbps",
      },
      {
        id: "4gv-d4",
        vol: "500 MB",
        price: "500 RWF",
        priceRaw: 500,
        validity: "1 day",
        speed: "Up to 20 Mbps",
      },
      {
        id: "4gv-d5",
        vol: "1 GB",
        price: "1000 RWF",
        priceRaw: 1000,
        validity: "1 day",
        speed: "Up to 30 Mbps",
      },
    ],
    weekly: [
      {
        id: "4gv-w1",
        vol: "1 GB",
        price: "1,500 RWF",
        priceRaw: 1500,
        validity: "7 days",
        speed: "Up to 20 Mbps",
      },
      {
        id: "4gv-w2",
        vol: "3 GB",
        price: "2,000 RWF",
        priceRaw: 2000,
        validity: "7 days",
        speed: "Up to 30 Mbps",
        popular: true,
      },
      {
        id: "4gv-w3",
        vol: "5 GB",
        price: "2,900 RWF",
        priceRaw: 2900,
        validity: "7 days",
        speed: "Up to 50 Mbps",
      },
    ],
    monthly: [
      {
        id: "4gv-m1",
        vol: "3 GB",
        price: "3,000 RWF",
        priceRaw: 3000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
    ],
  },
  "4g-special": {
    title: "4G Internet — special offers",
    desc: "Limited-time promotional bundles with extra value.",
    daily: [
      {
        id: "4gs-d1",
        vol: "1 GB",
        price: "300 RWF",
        priceRaw: 300,
        validity: "1 day",
        speed: "Up to 20 Mbps",
      },
    ],

    monthly: [
      {
        id: "4gs-m1",
        vol: "11 GB",
        price: "3,900 RWF",
        priceRaw: 3900,
        validity: "30 days",
        speed: "Up to 50 Mbps",
      },
      {
        id: "4gs-m2",
        vol: "30 GB",
        price: "8,900 RWF",
        priceRaw: 8900,
        validity: "30 days",
        speed: "Up to 100 Mbps",
        popular: true,
      },
      {
        id: "4gs-m3",
        vol: " For Smartphone",
        price: "16,000 RWF",
        priceRaw: 16000,
        validity: "30 days",
        speed: "Up to 100 Mbps",
        unlimited: true,
      },
    ],
  },
  "4g-home": {
    title: "4G Internet — Home Broadband",
    desc: "Stable 4G home internet with no fixed line needed. Plug in your router and get online in minutes.",
    monthly: [
      {
        id: "4gh-m1",
        vol: "20 Mbps",
        price: "20,000 RWF",
        priceRaw: 20000,
        validity: "30 days",
        popular: true,
        unlimited: true,
      },
      {
        id: "4gh-m2",
        vol: "50 Mbps",
        price: "35,000 RWF",
        priceRaw: 35000,
        validity: "30 days",
        unlimited: true,
      },
    ],
  },
  "4g-gahebuzo": {
    title: "4G Internet — Gahebuzo Packs",
    desc: "Gahebuzo monthly data packs — choose your volume and enjoy 30 days of browsing, streaming, and staying connected.",
    monthly: [
      {
        id: "4gg-m1",
        vol: "5 GB",
        price: "3,500 RWF",
        priceRaw: 3500,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m2",
        vol: "10 GB",
        price: "5,500 RWF",
        priceRaw: 5500,
        validity: "30 days",
        speed: "Up to 30 Mbps",
        popular: true,
      },
      {
        id: "4gg-m3",
        vol: "20 GB",
        price: "13,000 RWF",
        priceRaw: 13000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m4",
        vol: "30 GB",
        price: "15,000 RWF",
        priceRaw: 15000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m5",
        vol: "50 GB",
        price: "25,000 RWF",
        priceRaw: 25000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m6",
        vol: "100 GB",
        price: "50,000 RWF",
        priceRaw: 50000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
    ],
  },
  "4g-fixed": {
    title: "4G Internet — Fixed LTE SMEs",
    desc: "Fixed-speed home broadband over 4G. Consistent 50 Mbps all month, no data cap, no surprises.",
    monthly: [
      {
        id: "4gf-m1",
        vol: "50 Mbps",
        price: "200,000 RWF",
        priceRaw: 200000,
        validity: "30 days",
        speed: "Up to 50 Mbps",
      },
    ],
  },
  "4g-office": {
    title: "4G Internet — Office Broadband for SMEs",
    desc: "Dedicated 4G connectivity for offices. A reliable 50 Mbps connection to keep your team productive every day.",
    monthly: [
      {
        id: "4go-m1",
        vol: "50 Mbps",
        price: "49,000 RWF",
        priceRaw: 49000,
        validity: "30 days",
        speed: "Up to 50 Mbps",
      },
    ],
  },
  "4g-network": {
    title: "4G Internet — One Network",
    desc: "Guaranteed bandwidth plans for businesses that need a stable, always-on connection with a fixed speed floor.",
    monthly: [
      {
        id: "4gn-m1",
        vol: "3 Mbps",
        price: "96,000 RWF",
        priceRaw: 96000,
        validity: "30 days",
      },
      {
        id: "4gn-m2",
        vol: "5 Mbps",
        price: "120,000 RWF",
        priceRaw: 120000,
        validity: "30 days",
      },
    ],
  },
  "4g-education": {
    title: "4G Internet — Education Products",
    desc: "Affordable internet plans designed for schools and students — combining a data allowance with a steady base speed for learning tools and e-learning platforms.",
    monthly: [
      {
        id: "4ge-m1",
        vol: "1 GB + 3Mbps",
        price: "26,000 RWF",
        priceRaw: 26000,
        validity: "30 days",
      },
      {
        id: "4ge-m2",
        vol: "2 GB + 3Mbps",
        price: "37,000 RWF",
        priceRaw: 37000,
        validity: "30 days",
        popular: true,
      },
    ],
  },
  "4g-time": {
    title: "4G Internet — Time-Based Products(MUP)",
    desc: "Time-based bundles that give you a daily data allowance plus a continuous base speed — perfect for mixed usage throughout the day.",
    monthly: [
      {
        id: "4gt-m1",
        vol: "500 MB + 512 Kbps",
        price: "13,500 RWF",
        priceRaw: 13500,
        validity: "30 days",
      },
      {
        id: "4gt-m2",
        vol: "smart 500 MB + 512 Kbps",
        price: "17,000 RWF",
        priceRaw: 17000,
        validity: "30 days",
      },
      {
        id: "4gt-m3",
        vol: "2 GB/Day + 1Mbps private",
        price: "31,000 RWF",
        priceRaw: 31000,
        validity: "30 days",
      },
      {
        id: "4gt-m4",
        vol: "3 GB/Day + 2 Mbps",
        price: "65,000 RWF",
        priceRaw: 65000,
        validity: "30 days",
      },
      {
        id: "4gt-m5",
        vol: "4 GB/Day + 2 Mbps",
        price: "87,000 RWF",
        priceRaw: 87000,
        validity: "30 days",
      },
    ],
  },

  "volte-packages": {
    title: "VoLTE Packages",
    desc: "Enjoy high-quality voice calls over 4G with affordable packages.",
    daily: [
      {
        id: "vp-d1",
        vol: "Solektra Daily 1GB +300Min+50SMS",
        price: "550 RWF",
        priceRaw: 550,
        validity: "1 day",
      },
      {
        id: "vp-d2",
        vol: "Solektra 300Min +50SMS",
        price: "500 RWF",
        priceRaw: 500,
        validity: "1 day",
      },
    ],
    weekly: [
      {
        id: "vp-w1",
        vol: "Solekra 600Min +50SMS",
        price: "1,500 RWF",
        priceRaw: 1500,
        validity: "7 days",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "vp-m1",
        vol: "Solektra 11GB + 1000Min+50SMS",
        price: "4,900 RWF",
        priceRaw: 4900,
        validity: "30 days",
      },
      {
        id: "vp-m2",
        vol: "Solektra Agahebuzo 30GB + 1000Min+50SMS",
        price: "9,900 RWF",
        priceRaw: 9900,
        validity: "30 days",
      },
      {
        id: "vp-m3",
        vol: "Solektra Agahebuzo 30GB + 2500Min+200SMS",
        price: "11,000 RWF",
        priceRaw: 11000,
        validity: "30 days",
      },
      {
        id: "vp-m4",
        vol: "Solektra 2000Min+100SMS",
        price: "2,500 RWF",
        priceRaw: 2500,
        validity: "30 days",
      },
      {
        id: "vp-m5",
        vol: "Solektra 4600Min + 100SMS",
        price: "4,500 RWF",
        priceRaw: 4500,
        validity: "30 days",
      },
    ],
  },
  "devices-smartphones": {
    title: "Devices — smartphones",
    desc: "Reliable smartphones for every need and budget.",
    daily: [
      {
        id: "ds-1",
        image: "/assets/images/galaxya06.jpg",
        vol: "Samsung Galaxy A06",
        unit: "Phone",
        // price: "35,000 RWF",
        // priceRaw: 35000,
        validity: "1 day",
        speed: "RAM: 4 GB · ROM: 128 GB",
      },
      {
        id: "ds-2",
        image: "/assets/images/galaxya07.jpg",
        vol: "Samsung Galaxy A07",
        unit: "Phone",
        // price: "35,000 RWF",
        validity: "1 day",
        speed: "RAM: 4 GB · ROM: 128 GB",
      },
      {
        id: "ds-3",
        image: "/assets/images/galaxya11.jpg",
        vol: "Galaxy Tab A11+",
        unit: "Phone",
        // price: "35,000 RWF",
        // priceRaw: 35000,
        validity: "1 day",
        speed: "RAM: 6 GB · ROM: 128 GB",
      },
      {
        id: "ds-4",
        image: "/assets/images/galaxya56.jpg",
        vol: "Samsung Galaxy A56",
        unit: "Phone",
        // popular: true,
        speed: "RAM: 8 GB · ROM: 128 GB",
        validity: "1 day",
      },
      {
        id: "ds-5",
        image: "/assets/images/spark-50.webp",
        vol: "Techno Camon 50",
        unit: "Phone",
        // price: "35,000 RWF",
        // priceRaw: 35000,
        validity: "1 day",
        speed: "RAM: 8 GB · ROM: 256 GB",
      },
      {
        id: "ds-6",
        image: "/assets/images/A06jin.png",
        vol: "Itel A06",
        unit: "Phone",
        // price: "35,000 RWF",
        // priceRaw: 35000,
        validity: "1 day",
        speed: "RAM: 2 GB · ROM: 64 GB",
      },
      {
        id: "ds-7",
        image: "/assets/images/infinixHot50i.jpg",
        vol: "Infinix Hot 50i",
        unit: "Phone",
        // price: "35,000 RWF",
        // priceRaw: 35000,
        validity: "1 day",
        speed: "RAM: 4 GB · ROM: 128 GB",
      },
      {
        id: "ds-8",
        image: "/assets/images/infinixHot70.jpg",
        vol: "Infinix Hot 70",
        unit: "Phone",
        // price: "80,000 RWF",
        // priceRaw: 80000,
        speed: "RAM: 4 GB · ROM: 128 GB",
        validity: "1 day",
        // popular: true,
      },
      {
        id: "ds-9",
        image: "/assets/images/tecnoSpark50.jpg",
        vol: "Techno Spark 50",
        unit: "Phone",
        // price: "35,000 RWF",
        // priceRaw: 35000,
        validity: "1 day",
        speed: "RAM: 8 GB · ROM: 256 GB",
      },
      {
        id: "ds-10",
        image: "/assets/images/saprk40.webp",
        vol: "Techno Spark 40",
        unit: "Phone",
        // price: "80,000 RWF",
        // priceRaw: 80000,
        speed: "RAM: 4 GB · ROM: 128 GB",
        validity: "1 day",
        // popular: true,
      },
      {
        id: "ds-11",
        image: "/assets/images/pop20.webp",
        vol: "Techno Pop 20",
        unit: "Phone",
        // price: "80,000 RWF",
        // priceRaw: 80000,
        speed: "RAM: 4 GB · ROM: 128 GB",
        validity: "1 day",
        // popular: true,
      },
    ],
  },

  "devices-home": {
    title: "Routers — home",
    desc: "Compact 4G routers for households. Plug in and share Wi-Fi instantly.",
    daily: [
      {
        id: "rh-1",
        image: "/assets/images/pocketRoute.png",
        vol: "Mobile Router",
        // price: "50,000 RWF",
        // priceRaw: 25000,
        validity: "1 day",
        speed: "150 Mbps · 1500 mAh",
      },
      {
        id: "rh-2",
        image: "/assets/images/pocketRoute.png",
        vol: "Mobile Router",
        // price: "50,000 RWF",
        // priceRaw: 25000,
        validity: "1 day",
        speed: "300 Mbps · 3000 mAh",
      },
      {
        id: "rh-3",
        image: "/assets/images/router1.png",
        vol: "Wireless Router",
        // price: "45,000 RWF",
        // priceRaw: 45000,
        validity: "1 day",
        speed: "300 Mbps · 300 Wi-Fi speed",
        popular: true,
      },
    ],
  },
};
