import { Category, PlanSection } from "../types";

export const categories: Category[] = [
  {
    key: "4g",
    label: "4G Internet",
    icon: "wifi",
    subs: [
      { key: "volume", label: "Volume Based" },
      { key: "special", label: "Special Offers" },
      { key: "home", label: "Home Broadband" },
      { key: "gahebuzo", label: "Gahebuzo Packs" },
      { key: "fixed", label: "Fixed LTE SMEs" },
      { key: "office", label: "Office Broadband" },
      { key: "network", label: "One Network" },
      { key: "education", label: "Education Products" },
      { key: "time", label: "Time-Base(MUP)" },
    ],
  },
  {
    key: "volte",
    label: "VoLTE",
    icon: "router",
    subs: [{ key: "packages", label: "Solekrta Packages" }],
  },
  {
    key: "router",
    label: "Routers",
    icon: "router",
    subs: [
      { key: "home", label: "Home routers" },
      { key: "business", label: "Business routers" },
      { key: "pocket", label: "Pocket Wi-Fi" },
    ],
  },
  {
    key: "fiber",
    label: "Fiber",
    icon: "topology-star-3",
    subs: [
      { key: "home", label: "Home fiber" },
      { key: "business", label: "Business fiber" },
      { key: "enterprise", label: "Enterprise" },
    ],
  },
  {
    key: "devices",
    label: "Devices",
    icon: "device-mobile",
    subs: [
      { key: "smartphones", label: "Smartphones" },
      { key: "paygo", label: "PAYGO plans" },
      { key: "accessories", label: "Accessories" },
    ],
  },
];

export const plansData: Record<string, PlanSection> = {
  "4g-volume": {
    title: "4G Internet — volume based",
    desc: "Daily , weekly and monthly data bundles. Buy once and use until it expires.",
    daily: [
      {
        id: "4gv-d1",
        vol: "60 MB",
        price: "100 RWF",
        priceRaw: 100,
        validity: "1 day",
        speed: "Up to 10 Mbps",
      },
      {
        id: "4gv-d2",
        vol: "150 MB",
        price: "200 RWF",
        priceRaw: 200,
        validity: "1 day",
        speed: "Up to 10 Mbps",
        popular: true,
      },
      {
        id: "4gv-d3",
        vol: "300 MB",
        price: "300 RWF",
        priceRaw: 300,
        validity: "1 day",
        speed: "Up to 20 Mbps",
      },
      {
        id: "4gv-d4",
        vol: "500 MB",
        price: "500 RWF",
        priceRaw: 500,
        validity: "1 day",
        speed: "Up to 20 Mbps",
      },
      {
        id: "4gv-d5",
        vol: "1 GB",
        price: "1000 RWF",
        priceRaw: 1000,
        validity: "1 day",
        speed: "Up to 30 Mbps",
      },
    ],
    weekly: [
      {
        id: "4gv-w1",
        vol: "1 GB",
        price: "1,500 RWF",
        priceRaw: 1500,
        validity: "7 days",
        speed: "Up to 20 Mbps",
      },
      {
        id: "4gv-w2",
        vol: "3 GB",
        price: "2,000 RWF",
        priceRaw: 2000,
        validity: "7 days",
        speed: "Up to 30 Mbps",
        popular: true,
      },
      {
        id: "4gv-w3",
        vol: "5 GB",
        price: "2,900 RWF",
        priceRaw: 2900,
        validity: "7 days",
        speed: "Up to 50 Mbps",
      },
    ],
    monthly: [
      {
        id: "4gv-m1",
        vol: "3 GB",
        price: "3,000 RWF",
        priceRaw: 3000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
    ],
  },
  "4g-special": {
    title: "4G Internet — special offers",
    desc: "Limited-time promotional bundles with extra value.",
    daily: [
      {
        id: "4gs-d1",
        vol: "1 GB",
        price: "300 RWF",
        priceRaw: 300,
        validity: "1 day",
        speed: "Up to 20 Mbps",
      },
    ],

    monthly: [
      {
        id: "4gs-m1",
        vol: "11 GB",
        price: "3,900 RWF",
        priceRaw: 3900,
        validity: "30 days",
        speed: "Up to 50 Mbps",
      },
      {
        id: "4gs-m2",
        vol: "30 GB",
        price: "8,900 RWF",
        priceRaw: 8900,
        validity: "30 days",
        speed: "Up to 100 Mbps",
        popular: true,
      },
      {
        id: "4gs-m3",
        vol: " For Smartphone",
        price: "16,000 RWF",
        priceRaw: 16000,
        validity: "30 days",
        speed: "Up to 100 Mbps",
        unlimited: true,
      },
    ],
  },
  "4g-home": {
    title: "4G Internet — Home Broadband",
    desc: "Stable 4G home internet with no fixed line needed. Plug in your router and get online in minutes.",
    monthly: [
      {
        id: "4gh-m1",
        vol: "20 Mbps",
        price: "20,000 RWF",
        priceRaw: 20000,
        validity: "30 days",
        popular: true,
        unlimited: true,
      },
      {
        id: "4gh-m2",
        vol: "50 Mbps",
        price: "35,000 RWF",
        priceRaw: 35000,
        validity: "30 days",
        unlimited: true,
      },
    ],
  },
  "4g-gahebuzo": {
    title: "4G Internet — Gahebuzo Packs",
    desc: "Gahebuzo monthly data packs — choose your volume and enjoy 30 days of browsing, streaming, and staying connected.",
    monthly: [
      {
        id: "4gg-m1",
        vol: "5 GB",
        price: "3,500 RWF",
        priceRaw: 3500,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m2",
        vol: "10 GB",
        price: "5,500 RWF",
        priceRaw: 5500,
        validity: "30 days",
        speed: "Up to 30 Mbps",
        popular: true,
      },
      {
        id: "4gg-m3",
        vol: "20 GB",
        price: "13,000 RWF",
        priceRaw: 13000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m4",
        vol: "30 GB",
        price: "15,000 RWF",
        priceRaw: 15000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m5",
        vol: "50 GB",
        price: "25,000 RWF",
        priceRaw: 25000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
      {
        id: "4gg-m6",
        vol: "100 GB",
        price: "50,000 RWF",
        priceRaw: 50000,
        validity: "30 days",
        speed: "Up to 30 Mbps",
      },
    ],
  },
  "4g-fixed": {
    title: "4G Internet — Fixed LTE SMEs",
    desc: "Fixed-speed home broadband over 4G. Consistent 50 Mbps all month, no data cap, no surprises.",
    monthly: [
      {
        id: "4gf-m1",
        vol: "50 Mbps",
        price: "200,000 RWF",
        priceRaw: 200000,
        validity: "30 days",
        speed: "Up to 50 Mbps",
      },
    ],
  },
  "4g-office": {
    title: "4G Internet — Office Broadband for SMEs",
    desc: "Dedicated 4G connectivity for offices. A reliable 50 Mbps connection to keep your team productive every day.",
    monthly: [
      {
        id: "4go-m1",
        vol: "50 Mbps",
        price: "49,000 RWF",
        priceRaw: 49000,
        validity: "30 days",
        speed: "Up to 50 Mbps",
      },
    ],
  },
  "4g-network": {
    title: "4G Internet — One Network",
    desc: "Guaranteed bandwidth plans for businesses that need a stable, always-on connection with a fixed speed floor.",
    monthly: [
      {
        id: "4gn-m1",
        vol: "3 Mbps",
        price: "96,000 RWF",
        priceRaw: 96000,
        validity: "30 days",
      },
      {
        id: "4gn-m2",
        vol: "5 Mbps",
        price: "120,000 RWF",
        priceRaw: 120000,
        validity: "30 days",
      },
    ],
  },
  "4g-education": {
    title: "4G Internet — Education Products",
    desc: "Affordable internet plans designed for schools and students — combining a data allowance with a steady base speed for learning tools and e-learning platforms.",
    monthly: [
      {
        id: "4ge-m1",
        vol: "1 GB + 3Mbps",
        price: "26,000 RWF",
        priceRaw: 26000,
        validity: "30 days",
      },
      {
        id: "4ge-m2",
        vol: "2 GB + 3Mbps",
        price: "37,000 RWF",
        priceRaw: 37000,
        validity: "30 days",
        popular: true,
      },
    ],
  },
  "4g-time": {
    title: "4G Internet — Time-Based Products(MUP)",
    desc: "Time-based bundles that give you a daily data allowance plus a continuous base speed — perfect for mixed usage throughout the day.",
    monthly: [
      {
        id: "4gt-m1",
        vol: "500 MB + 512 Kbps",
        price: "13,500 RWF",
        priceRaw: 13500,
        validity: "30 days",
      },
      {
        id: "4gt-m2",
        vol: "smart 500 MB + 512 Kbps",
        price: "17,000 RWF",
        priceRaw: 17000,
        validity: "30 days",
      },
      {
        id: "4gt-m3",
        vol: "2 GB/Day + 1Mbps private",
        price: "31,000 RWF",
        priceRaw: 31000,
        validity: "30 days",
      },
      {
        id: "4gt-m4",
        vol: "3 GB/Day + 2 Mbps",
        price: "65,000 RWF",
        priceRaw: 65000,
        validity: "30 days",
      },
      {
        id: "4gt-m5",
        vol: "4 GB/Day + 2 Mbps",
        price: "87,000 RWF",
        priceRaw: 87000,
        validity: "30 days",
      },
    ],
  },

  "volte-packages": {
    title: "VoLTE Packages",
    desc: "Compact 4G routers for households. Plug in and share Wi-Fi instantly.",
    daily: [
      {
        id: "vp-d1",
        vol: "Solektra Daily 1GB +300Min+50SMS",
        price: "550 RWF",
        priceRaw: 550,
        validity: "1 day",
      },
      {
        id: "vp-d2",
        vol: "Solektra 300Min +50SMS",
        price: "500 RWF",
        priceRaw: 500,
        validity: "1 day",
      },
    ],
    weekly: [
      {
        id: "vp-w1",
        vol: "Solekra 600Min +50SMS",
        price: "1,500 RWF",
        priceRaw: 1500,
        validity: "7 days",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "vp-m1",
        vol: "Solektra 11GB + 1000Min+50SMS",
        price: "4,900 RWF",
        priceRaw: 4900,
        validity: "30 days",
      },
      {
        id: "vp-m2",
        vol: "Solektra Agahebuzo 30GB + 1000Min+50SMS",
        price: "9,900 RWF",
        priceRaw: 9900,
        validity: "30 days",
      },
      {
        id: "vp-m3",
        vol: "Solektra Agahebuzo 30GB + 2500Min+200SMS",
        price: "11,000 RWF",
        priceRaw: 11000,
        validity: "30 days",
      },
      {
        id: "vp-m4",
        vol: "Solektra 2000Min+100SMS",
        price: "2,500 RWF",
        priceRaw: 2500,
        validity: "30 days",
      },
      {
        id: "vp-m5",
        vol: "Solektra 4600Min + 100SMS",
        price: "4,500 RWF",
        priceRaw: 4500,
        validity: "30 days",
      },
    ],
  },

  "router-home": {
    title: "Routers — home",
    desc: "Compact 4G routers for households. Plug in and share Wi-Fi instantly.",
    daily: [
      {
        id: "rh-1",
        vol: "Basic Router",
        price: "25,000 RWF",
        priceRaw: 25000,
        validity: "One-time",
        speed: "150 Mbps · 16 devices",
      },
    ],
    weekly: [
      {
        id: "rh-2",
        vol: "Standard Router",
        price: "45,000 RWF",
        priceRaw: 45000,
        validity: "One-time",
        speed: "300 Mbps · 32 devices",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "rh-3",
        vol: "Premium Router",
        price: "75,000 RWF",
        priceRaw: 75000,
        validity: "One-time",
        speed: "600 Mbps · 64 devices",
      },
    ],
  },
  "router-business": {
    title: "Routers — business",
    desc: "High-throughput routers with enterprise features and priority support.",
    daily: [
      {
        id: "rb-1",
        vol: "Business 300",
        price: "80,000 RWF",
        priceRaw: 80000,
        validity: "One-time",
        speed: "300 Mbps dual-band",
      },
    ],
    weekly: [
      {
        id: "rb-2",
        vol: "Business 600",
        price: "120,000 RWF",
        priceRaw: 120000,
        validity: "One-time",
        speed: "600 Mbps dual-band",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "rb-3",
        vol: "Business Pro",
        price: "200,000 RWF",
        priceRaw: 200000,
        validity: "One-time",
        speed: "1 Gbps tri-band",
      },
    ],
  },
  "router-pocket": {
    title: "Routers — pocket Wi-Fi",
    desc: "Take your network anywhere. Battery-powered portable hotspots.",
    daily: [
      {
        id: "rp-1",
        vol: "Pocket 150",
        price: "18,000 RWF",
        priceRaw: 18000,
        validity: "One-time",
        speed: "150 Mbps · 10 devices",
      },
    ],
    weekly: [
      {
        id: "rp-2",
        vol: "Pocket 300",
        price: "30,000 RWF",
        priceRaw: 30000,
        validity: "One-time",
        speed: "300 Mbps · 16 devices",
        popular: true,
      },
    ],
    monthly: [],
  },
  "fiber-home": {
    title: "Fiber — home",
    desc: "Gigabit fiber delivered directly to your home.",
    daily: [
      {
        id: "fh-1",
        vol: "10 Mbps",
        unit: "Home",
        price: "15,000 RWF/mo",
        priceRaw: 15000,
        validity: "Monthly",
        speed: "Symmetric 10 Mbps",
      },
    ],
    weekly: [
      {
        id: "fh-2",
        vol: "50 Mbps",
        unit: "Home",
        price: "30,000 RWF/mo",
        priceRaw: 30000,
        validity: "Monthly",
        speed: "Symmetric 50 Mbps",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "fh-3",
        vol: "100 Mbps",
        unit: "Home",
        price: "50,000 RWF/mo",
        priceRaw: 50000,
        validity: "Monthly",
        speed: "Symmetric 100 Mbps",
      },
      {
        id: "fh-4",
        vol: "500 Mbps",
        unit: "Home",
        price: "90,000 RWF/mo",
        priceRaw: 90000,
        validity: "Monthly",
        speed: "Symmetric 500 Mbps",
      },
    ],
  },
  "fiber-business": {
    title: "Fiber — business",
    desc: "Dedicated business fiber with SLA and 24/7 support.",
    daily: [
      {
        id: "fb-1",
        vol: "100 Mbps",
        unit: "Biz",
        price: "80,000 RWF/mo",
        priceRaw: 80000,
        validity: "Monthly",
        speed: "Symmetric 100 Mbps",
      },
    ],
    weekly: [
      {
        id: "fb-2",
        vol: "500 Mbps",
        unit: "Biz",
        price: "150,000 RWF/mo",
        priceRaw: 150000,
        validity: "Monthly",
        speed: "Symmetric 500 Mbps",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "fb-3",
        vol: "1 Gbps",
        unit: "Biz",
        price: "250,000 RWF/mo",
        priceRaw: 250000,
        validity: "Monthly",
        speed: "Symmetric 1 Gbps",
      },
    ],
  },
  "fiber-enterprise": {
    title: "Fiber — enterprise",
    desc: "Custom capacity and dedicated lines for large organisations.",
    daily: [],
    weekly: [
      {
        id: "fe-1",
        vol: "10 Gbps",
        price: "Contact us",
        priceRaw: 0,
        validity: "Custom",
        speed: "Symmetric 10 Gbps",
        popular: true,
      },
    ],
    monthly: [],
  },
  "devices-smartphones": {
    title: "Devices — smartphones",
    desc: "Reliable smartphones for every need and budget.",
    daily: [
      {
        id: "ds-1",
        vol: "Entry",
        unit: "Phone",
        price: "35,000 RWF",
        priceRaw: 35000,
        validity: "One-time",
        speed: "4G ready · 4000 mAh",
      },
    ],
    weekly: [
      {
        id: "ds-2",
        vol: "Mid-range",
        unit: "Phone",
        price: "80,000 RWF",
        priceRaw: 80000,
        validity: "One-time",
        speed: "4G+ · 6 GB RAM",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "ds-3",
        vol: "Flagship",
        unit: "Phone",
        price: "200,000 RWF",
        priceRaw: 200000,
        validity: "One-time",
        speed: "5G ready · 12 GB RAM",
      },
    ],
  },
  "devices-paygo": {
    title: "Devices — PAYGO plans",
    desc: "Own a device through flexible pay-as-you-go instalments.",
    daily: [
      {
        id: "dp-1",
        vol: "Basic",
        unit: "PAYGO",
        price: "3,000 RWF/wk",
        priceRaw: 3000,
        validity: "12 weeks",
        speed: "Entry smartphone",
      },
    ],
    weekly: [
      {
        id: "dp-2",
        vol: "Standard",
        unit: "PAYGO",
        price: "5,000 RWF/wk",
        priceRaw: 5000,
        validity: "16 weeks",
        speed: "Mid-range smartphone",
        popular: true,
      },
    ],
    monthly: [
      {
        id: "dp-3",
        vol: "Premium",
        unit: "PAYGO",
        price: "15,000 RWF/mo",
        priceRaw: 15000,
        validity: "12 months",
        speed: "Flagship smartphone",
      },
    ],
  },
  "devices-accessories": {
    title: "Devices — accessories",
    desc: "SIM cards, cases, chargers, and add-ons.",
    daily: [
      {
        id: "da-1",
        vol: "SIM card",
        price: "500 RWF",
        priceRaw: 500,
        validity: "One-time",
        speed: "4G nano SIM",
      },
    ],
    weekly: [
      {
        id: "da-2",
        vol: "Fast charger",
        price: "8,000 RWF",
        priceRaw: 8000,
        validity: "One-time",
        speed: "65W USB-C",
      },
    ],
    monthly: [
      {
        id: "da-3",
        vol: "Phone case",
        price: "5,000 RWF",
        priceRaw: 5000,
        validity: "One-time",
        speed: "Shockproof · universal fit",
      },
    ],
  },
};
